export const tests = [
  ["2 + 2 is 4", () => 2 + 2],
  ["undefined is supported", () => {}],
  ["lets test overwrite", () => "something else"],
  [
    "adding a new one",
    () => ({
      hej: "asdf new here",
      lets: "see ",
      ha: 1,
      l2: 3,
      e: 5,
      g: 0,
      u: 5,
      rtg: 5,
      wegfre: 5,
      wegfr: 5,
      wegfe: 5,
      wegre: 5,
      egfe: 5,
      wgre: 5,
      wefe: 5,
      wegr: 5,
      efe: 5,
      wre: 5,
      wgr: 5,
      were: 5,
      bd: 5,
      sd: 5,
      d: 2,
    }),
  ],
  [
    "adding a short one",
    () => ({
      hej: "asdf new here",
      lets: "see ",
    }),
  ],
]
